version: "3.7"
services:
  postgres-server:
    image: library/postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: Password1
    networks:
      - archesky
  keycloak-server:
    image: jboss/keycloak:latest
    ports:
      - "8180:8080"
    environment:
      DB_ADDR: postgres-server
      DB_PORT: 5432
      DB_USER: postgres
      DB_VENDOR: postgres
      DB_PASSWORD: Password1
      DB_DATABASE: postgres
      KEYCLOAK_USER: root
      KEYCLOAK_PASSWORD: Password1
    links:
      - postgres-server
    depends_on:
      - postgres-server
    networks:
      - archesky
networks:
  archesky:
